#!/bin/bash
# Laravel+Docker dev-preview pool adapter.
#
# Problem: spinning up a fresh per-worktree preview stack is heavy (offset
# juggling, per-env DB restore, vendor/build bootstrap) and concurrent agent
# sessions step on each other's ports/DB names.
#
# Solution: a FIXED pool of N slots whose number matches the port (slotN ->
# offset 20+N -> http://localhost:302N by default), all pointed at the SHARED
# `${DB_PREFIX}_dev` DB (no per-slot restore), plus a lease table so only one
# worktree/session owns a slot at a time.
#
# State (shared across every worktree, survives worktree deletion):
#   $STATE_DIR/pool.tsv    lease table
#   $STATE_DIR/pool.lock/  mkdir-based mutex (macOS has no flock)
#   $STATE_DIR/warm/       branch-agnostic vendor/build cache (seeded by warm)
#
# Config-driven (see config.example.yaml). The literal "AppOne" stack is
# one consumer of this adapter; any Laravel+Docker app fits.
#
# Usage (run claim/release from a worktree's app1/ dir):
#   pool.sh list
#   pool.sh claim [label]
#   pool.sh release [slot]
#   pool.sh warm | cool | gc

set -euo pipefail

# Claude/non-interactive shells lack /usr/local/bin on PATH; bare `docker`
# then resolves to nothing and gc/list mis-judge containers as absent,
# corrupting the lease table. Guarantee docker is findable.
export PATH="/usr/local/bin:/opt/homebrew/bin:$PATH"

_adir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Load YAML config -> env vars (NAME, STATE_DIR, DB_*, APP_*, POOLS_DEV_*, ...).
source "$_adir/load-config.sh"
POOL_TAG=pool
TABLE="$STATE_DIR/pool.tsv"
LOCK="$STATE_DIR/pool.lock"
WARM_DIR="$STATE_DIR/warm"
SLOTS=("${POOLS_DEV_SLOTS[@]}")
OFFSETS=("${POOLS_DEV_OFFSETS[@]}")
source "$_adir/pool-core.sh"

# ---- adapter-specific helpers ---------------------------------------------

# Shared dev DB = whatever publishes host :$DB_DEV_HOST_PORT.
dev_db_up() {
  docker ps --format '{{.Ports}}' 2>/dev/null \
    | grep -q "0\.0\.0\.0:${DB_DEV_HOST_PORT}->" \
    || nc -z localhost "$DB_DEV_HOST_PORT" 2>/dev/null
}

warm_ready() { [ -d "$WARM_DIR/vendor" ] && [ -d "$WARM_DIR/public-build" ]; }

lock_matches() { # <app-subdir absolute path>: composer.lock == warm baseline?
  [ -f "$WARM_DIR/composer.lock.sha" ] || return 1
  [ "$(shasum "$1/composer.lock" 2>/dev/null | cut -d' ' -f1)" \
    = "$(cat "$WARM_DIR/composer.lock.sha")" ]
}

# First built image matching the container prefix, or a synthesized fallback.
ff_image() {
  docker images --format '{{.Repository}}' \
    | grep -m1 "${APP_CONTAINER_PREFIX}.*${APP_CONTAINER_PREFIX}" \
    || echo "${APP_CONTAINER_PREFIX}-${SLOTS[0]}-${APP_CONTAINER_PREFIX}"
}

# Per-slot compose override: point app at shared dev DB, mount warm cache when
# the worktree's composer.lock matches the warm baseline.
write_override() { # app1 slot include_warm
  local main="${APP_CONTAINER_PREFIX}"
  { echo "# Auto-generated by pool.sh ($2) -- deleted on release/cool."
    echo "services:"
    echo "  ${main}:"
    echo "    environment:"
    echo "      - DB_HOST=host.docker.internal"
    echo "      - DB_PORT=${DB_DEV_HOST_PORT}"
    echo "      - DB_DATABASE=${DB_PREFIX}_dev"
    echo "      - DB_USERNAME=root"
    echo "      - DB_PASSWORD=${DB_PASSWORD}"
    if [ "${3:-0}" = 1 ] && warm_ready; then
      echo "    volumes:"
      echo "      - $WARM_DIR/vendor:/app/vendor"
      echo "      - $WARM_DIR/public-build:/app/public/build"
    fi
  } > "$1/docker-compose.${2}.local.yml"
}

# Tear down every per-slot container (main + sidecars), by name.
docker_rm_slot_containers() { # slot
  local slot="$1" names=("${APP_CONTAINER_PREFIX}-${slot}")
  local p; for p in "${SIDECAR_CONTAINER_PREFIXES[@]:-${APP_SIDECAR_CONTAINER_PREFIXES[@]:-}}"; do
    names+=("${p}-${slot}")
  done
  docker rm -f "${names[@]}" 2>/dev/null || true
}

# ---- commands --------------------------------------------------------------

cmd_claim() {
  init_table
  local label="${1:-}"
  local app1 branch host slot=""
  app1=$(wt_app1)
  branch=$(wt_branch "$app1")
  host=$(hostname -s 2>/dev/null || echo localhost)

  if ! dev_db_up; then
    echo "pool: WARNING - nothing publishing host :${DB_DEV_HOST_PORT}. The shared" >&2
    echo "      ${DB_PREFIX}_dev DB must be up (launch the 'dev' stack) or slots can't connect." >&2
  fi

  lock
  slot=$(find_my_slot "$app1")
  [ -z "$slot" ] && slot=$(find_free_slot)
  if [ -z "$slot" ]; then
    unlock
    echo "pool: all ${#SLOTS[@]} slots leased. 'pool.sh list' / 'pool.sh gc'." >&2
    exit 1
  fi
  local off port
  off=$(awk -F'\t' -v s="$slot" '$1==s{print $2}' "$TABLE")
  port=$((3000 + off))
  set_row "$slot" leased "$app1" "$branch" "${label:--}" "$(date -u +%FT%TZ)" "$host"
  unlock

  echo "pool: leased $slot (offset $off) -> http://localhost:$port for $branch"

  reserve_port_file "$app1" "$slot" "$off"

  local fa="$app1/$APP_SUBDIR" use_warm=0
  if warm_ready && lock_matches "$fa"; then
    use_warm=1
    echo "pool: composer.lock matches warm cache -> mounting shared vendor/build (no install)"
  fi
  write_override "$app1" "$slot" "$use_warm"

  if [ $use_warm -eq 0 ]; then
    if ! warm_ready; then
      echo "pool: not warmed (run 'pool.sh warm') -> per-worktree bootstrap"
    else
      echo "pool: worktree composer.lock differs from warm baseline -> per-worktree composer install"
    fi
    if [ ! -d "$fa/vendor" ]; then
      echo "pool: vendor/ missing -> composer install (one-off container, ~minutes)"
      docker run --rm --entrypoint sh -v "$fa":/app -w /app "$(ff_image):latest" \
        -c "composer install --no-interaction --prefer-dist" \
        || echo "pool: composer install failed (no built image? run 'pool.sh warm' first)" >&2
    fi
    if [ ! -d "$fa/public/build" ] && [ -d "$APP_MAIN_DIR/$APP_SUBDIR/public/build" ]; then
      echo "pool: copying public/build from main checkout"
      cp -R "$APP_MAIN_DIR/$APP_SUBDIR/public/build" "$fa/public/"
    fi
  fi
  if [ ! -e "$fa/.env" ]; then
    if [ -f "$fa/.env.dev" ]; then
      sed 's/^DB_HOST=.*/DB_HOST=host.docker.internal/' "$fa/.env.dev" > "$fa/.env.${slot}"
      ( cd "$fa" && ln -sf ".env.${slot}" .env )
    else
      echo "pool: WARNING - no $fa/.env or .env.dev; app may fail to boot (no APP_KEY)" >&2
    fi
  fi

  echo "pool: launching $slot stack from $app1 ..."
  ( cd "$app1" && "./${APP_LAUNCH_SCRIPT}" "$slot" \
      -f "docker-compose.${slot}.local.yml" \
      up -d --no-deps --build "${APP_COMPOSE_SERVICES[@]}" )
  ( cd "$app1" && docker exec "${APP_CONTAINER_PREFIX}-${slot}" \
      php artisan config:clear >/dev/null 2>&1 || true )

  cat <<MSG

pool: $slot is up.
  App:   http://localhost:$port
  Free:  pool.sh release $slot   (run from anywhere)
MSG
}

cmd_release() {
  init_table
  local slot="${1:-}" app1 row
  if [ -z "$slot" ]; then
    app1=$(wt_app1)
    slot=$(find_my_slot "$app1")
    [ -z "$slot" ] && { echo "pool: this worktree owns no slot (pass a slot name)"; exit 0; }
  fi
  row=$(awk -F'\t' -v s="$slot" '$1==s{print}' "$TABLE")
  [ -z "$row" ] && { echo "pool: unknown slot '$slot'" >&2; exit 1; }
  app1=$(echo "$row" | cut -f5)

  if [ -d "$app1" ]; then
    echo "pool: tearing down $slot stack ..."
    ( cd "$app1" && "./${APP_LAUNCH_SCRIPT}" "$slot" \
        -f "docker-compose.${slot}.local.yml" down ) 2>/dev/null || true
    rm -f "$app1/docker-compose.${slot}.local.yml" \
          "$app1/$APP_SUBDIR/.env.${slot}"
    clear_port_file "$app1" "$slot"
  else
    echo "pool: worktree $app1 gone; removing containers by name"
    docker_rm_slot_containers "$slot"
  fi

  lock; set_row "$slot" free - - - - -; normalize_table; unlock
  echo "pool: $slot freed."
}

cmd_gc() {
  init_table
  local freed=0
  while IFS=$'\t' read -r slot off port status wt rest; do
    [ "$status" = "leased" ] || continue
    if [ ! -d "$wt" ] || ! docker ps -a --format '{{.Names}}' \
         | grep -qx "${APP_CONTAINER_PREFIX}-${slot}"; then
      echo "pool: reclaiming stale $slot (worktree gone or container absent)"
      [ -d "$wt" ] && rm -f "$wt/docker-compose.${slot}.local.yml" || true
      docker_rm_slot_containers "$slot"
      lock; set_row "$slot" free - - - - -; unlock
      freed=$((freed+1))
    fi
  done < <(tail -n +2 "$TABLE")
  lock; normalize_table; unlock
  echo "pool: gc done ($freed reclaimed)."
}

# Build the branch-agnostic warm cache + image, then start all free slots
# bound to the main checkout so claim is an instant rebind.
cmd_warm() {
  init_table
  local mfa="$APP_MAIN_DIR/$APP_SUBDIR"
  [ -d "$mfa/vendor" ] || { echo "pool: $mfa has no vendor/ -- composer install in main first" >&2; exit 1; }
  [ -d "$mfa/public/build" ] || { echo "pool: $mfa has no public/build -- npm run build in main first" >&2; exit 1; }

  echo "pool: seeding warm cache from main checkout ..."
  mkdir -p "$WARM_DIR"
  rsync -a --delete "$mfa/vendor/"       "$WARM_DIR/vendor/"
  rsync -a --delete "$mfa/public/build/" "$WARM_DIR/public-build/"
  shasum "$mfa/composer.lock"     | cut -d' ' -f1 > "$WARM_DIR/composer.lock.sha"
  shasum "$mfa/package-lock.json" 2>/dev/null | cut -d' ' -f1 > "$WARM_DIR/package-lock.sha" || true
  echo "pool: warm vendor $(du -sh "$WARM_DIR/vendor" | cut -f1) (composer.lock $(cat "$WARM_DIR/composer.lock.sha" | cut -c1-12))"

  dev_db_up || echo "pool: WARNING - nothing on host :${DB_DEV_HOST_PORT}; warmed apps will 500 on DB calls." >&2

  touch "$APP_MAIN_DIR/.dc-ports"
  local i
  for i in "${!SLOTS[@]}"; do
    local slot="${SLOTS[$i]}" off="${OFFSETS[$i]}" port=$((3000 + OFFSETS[$i]))
    local owner; owner=$(owner_of "$slot")
    [ "$owner" = leased ]  && { echo "pool: $slot LEASED -- skipping"; continue; }
    [ "$owner" = blocked ] && { echo "pool: $slot BLOCKED (port held by legacy lease) -- skipping"; continue; }
    grep -q "^${slot}=" "$APP_MAIN_DIR/.dc-ports" 2>/dev/null \
      || echo "${slot}=${off}" >> "$APP_MAIN_DIR/.dc-ports"
    write_override "$APP_MAIN_DIR" "$slot" 1
    echo "pool: building+starting $slot (first slot builds the image, rest reuse cache) ..."
    ( cd "$APP_MAIN_DIR" && "./${APP_LAUNCH_SCRIPT}" "$slot" -f "docker-compose.${slot}.local.yml" \
        up -d --no-deps --build "${APP_COMPOSE_SERVICES[@]}" )
    ( cd "$APP_MAIN_DIR" && docker exec "${APP_CONTAINER_PREFIX}-${slot}" \
        php artisan optimize >/dev/null 2>&1 || true )
    echo "pool: $slot ready -> http://localhost:$port"
  done
  echo "pool: warm complete. claim rebinds a free slot to a worktree instantly."
}

cmd_cool() {
  init_table
  local slot owner
  for slot in "${SLOTS[@]}"; do
    owner=$(owner_of "$slot")
    [ "$owner" = leased ]  && { echo "pool: $slot LEASED -- skipping (use release)"; continue; }
    [ "$owner" = blocked ] && { echo "pool: $slot BLOCKED -- skipping"; continue; }
    ( cd "$APP_MAIN_DIR" && "./${APP_LAUNCH_SCRIPT}" "$slot" \
        -f "docker-compose.${slot}.local.yml" down ) 2>/dev/null || true
    rm -f "$APP_MAIN_DIR/docker-compose.${slot}.local.yml"
    clear_port_file "$APP_MAIN_DIR" "$slot"
  done
  echo "pool: cooled (free slots down; leased untouched; warm cache kept)."
}

case "${1:-list}" in
  list)    cmd_list ;;
  claim)   shift; cmd_claim "$@" ;;
  release) shift; cmd_release "$@" ;;
  warm)    cmd_warm ;;
  cool)    cmd_cool ;;
  gc)      cmd_gc ;;
  *) echo "usage: pool.sh {list|claim [label]|release [slot]|warm|cool|gc}" >&2; exit 1 ;;
esac
